services:
  workspace:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_NAME}-workspace
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - symfony

  postgres:
    image: postgres:15
    container_name: ${APP_NAME}-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - symfony

  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    ports:
      - "9004:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - workspace
    networks:
      - symfony

networks:
  symfony:

volumes:
  pgdata: